export enum OrderStepEnum {
	START = 1,
	CHECK_SIM_BEFORE_REG = 2,
	OCR = 3,
	GENERATE_CUSTOMER_CODE = 4,
  GENERATE_SECRET_KEY = 5,
	CHECK_PROFILE = 6,
	GET_OTP = 7,
	CONFIRM_OTP = 8,
	GENERATE_CONTRACT_NUMBER = 9,
	GENERATE_CONTRACT = 10,
  SUBMIT_CONTRACT_SIGNATURE = 11,
  CONTRACT_SIGNING_CHECKER = 12,
  ACTIVATE = 13,
	CHECK_SIM_AFTER_REG = 14,
}

export enum OrderStatusEnum {
	INIT = 1,
	SUCCESS = 2,
	FAILURE = 3,
}

export enum OrderTypeEnum {
	NORMAL = 1,
}
