export enum ActionLogTypeEnum {
	UNKNOWN = 1,
	VNSKY_LOGIN = 2,
	VNSKY_REFRESH_TOKEN = 3,
	VNSKY_PROFILE = 4,
	VNSKY_CHECK_SIM = 5,
	VNSKY_OCR = 6,
	VNSKY_GEN_CUSTOMER_CODE = 7,
	VNSKY_GEN_SECRET_KEY = 8,
	VNSKY_CHECK_PROFILE = 9,
	VNSKY_GEN_CONTRACT_NUMBER = 10,
	VNSKY_GEN_CONTRACT = 11,
	VNSKY_SUBMIT_CONTRACT_SIGNATURE = 12,
	VNSKY_CONTRACT_SIGNING_CHECKER = 13,
	VNSKY_ACTIVATE = 14,
	VNSKY_GET_OTP = 15,
	VNSKY_CONFIRM_OTP = 16,
}

export enum ActionLogStatusEnum {
	SUCCESS = 1,
	FAILURE = 2,
}
